name: nova
channels:
  - defaults
dependencies:
  - python=3.9.7
  - pip=22.2.2
  - pip:
    - jupyterlab==3.5.0
    - matplotlib==3.5.2
    - numpy==1.22.4
    - pandas==1.3.5
    - python-levenshtein==0.12.2
    - python-ternary==1.0.8
    - scikit-learn==1.1.2
    - scipy==1.7.3
    - seaborn==0.11.2
    - statsmodels==0.13.1
    - thefuzz==0.19.0
